### ISSUE TITLE
Switch formatting rules from typescript-eslint to ESLint Stylistic

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [RebeccaStevens/eslint-config-rebeccastevens#1204]
## Suggestion

👋 Coming over from https://github.com/typescript-eslint/typescript-eslint/issues/9501: I wanted to try out typescript-eslint's v8 beta on [eslint-plugin-functional](https://github.com/eslint-functional/eslint-plugin-functional), but:

https://github.com/RebeccaStevens/eslint-config-rebeccastevens/blob/c6577a7daeb329920f51cc44fe6024f37bfab382/src/plugins/typescript.ts#L40

typescript-eslint deprecated those formatting rules in v6.16.0 (https://typescript-eslint.io/blog/deprecating-formatting-rules) and removed them in v8. So this eslint-config will need to have the rules switched over to their [**ESLint Stylistic**](https://eslint.style) counterparts in order to work with typescript-eslint v8.

**Comment by RebeccaStevens** [comment]
Hey, those changes have all been made on the next branch #1177
I've been testing them out that branch on various projects and all is going well :)

Essentially this repo is just waiting for everything to be released at stable before doing its merge.
